### ISSUE TITLE
Bower registration

### ISSUE THREAD

**Issue by kossebau** [kogmbh/ViewerJS_release#1]
Readding this issue from @desandro as I had to recreate the repo due to git(hub) not liking it if the initial commit is redone by a forced push:

From https://github.com/bower/bower/issues/120#issuecomment-69328333, @kossebau has requested that `viewerjs` be un-registered from [aurigadl/Viewer.js](https://github.com/aurigadl/Viewer.js). @aurigad, it sounds like this is a legitimate request. But I'd like to see if we can get your input before I re-register the package to this repo.

The `viewerjs` bower package has over 6000 hits. Switching it over to this repo could break compatibility as this repo does not have 0.2.0 and 0.2.1 releases.

**Comment by kossebau** [comment]
0.2.0 was not yet covered by a bower.json file and also missing the built files.
Recreated this repo with a new commit added that is tagged as "v0.2.1" and from which the same files are installed for bower as with the bower package from @aurigad for "v0.2.1" (but with updated metadata in the bower,json file).

**Comment by kossebau** [comment]
Hi @desandro, I fear there will be no feedback from @aurigadl. I have tried to contact the person behind since November by the email as registered for the account. And also by mentioning the name on the bower re-register comment, but also did not trigger any reaction.
If you look at https://github.com/aurigadl?tab=activity it seems this account is dead and the person behind not interested anymore.
So please consider re-registering soon, now that there is also support for the previous used version.
And then we finally can satisfy the now-and-then nagging bower users that wants to get an updated and maintained repo of ViewerJS that they simply could use the central bower registry :)

**Comment by desandro** [comment]
You got it. `viewerjs` has been re-registered to `git://github.com/kogmbh/ViewerJS_release.git` :arrow_right:

**Comment by kossebau** [comment]
Jay. Thanks^Wgood :)

**Comment by aurigadl** [comment]
hello, I have not the original project. I have stored in the repository the result of the steps and the publication of the final result and used it in bower.
what do you need to modify?
